### PR TITLE
Adapt to https://github.com/coq/coq/pull/19149

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19149 this is backward compatible and can be merged right away.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
A note for future reference: Before merging this PR, `.* */ //` was already at level 0 (according to `Print Grammar constr` in Coq 8.19.1), so I expect that merging it should make no difference.
The `.* */ x` notation for funspecs, however, is at level 200. Putting both of them at level 200 does not work. Putting both of them at level 0 seems to work and might be desirable if there's a requirement to put both at the same level.

**Comment by proux01** [comment]
Currently not having them at the same level only generates a warning. It may become more problematic the day we'll remove the recovery thing in camlp5 (but we are not there yet).

**Comment by proux01** [comment]
BTW, in what time frame can we expect the rupicola and fiat-crypto submodules to be updated nowadays?

**Comment by samuelgruetter** [comment]
> BTW, in what time frame can we expect the rupicola and fiat-crypto submodules to be updated nowadays?

We recently set up automerge for successful dependabot PRs, which run nightly, so if it all works, this change should be in fiat-crypto by tomorrow, without requiring any further manual action

**Pull request merged**
