### PR TITLE
adapt to coq/coq#17281

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
```
  fatal: remote error: upload-pack: not our ref 8122eac09625561edeeb2d2841dab3dcaa926026
  From https://github.com/tchajed/coq-record-update
```
@samuelgruetter do we still use that library?

**Comment by samuelgruetter** [comment]
We're not using that library any more at the moment.

But overall, the log looks quite confused:

```
Fetching submodule deps/riscv-coq
  fatal: remote error: upload-pack: not our ref 23c0acf4bbd42a195fc48d03b65154283444fa71
  From https://github.com/mit-plv/kami
...
  fatal: remote error: upload-pack: not our ref 8122eac09625561edeeb2d2841dab3dcaa926026
  From https://github.com/tchajed/coq-record-update
...
  Errors during submodule fetch:
  	deps/riscv-coq
  	deps/coqutil
  Error: Process completed with exit code 1.
```

And this PR sets kami to https://github.com/mit-plv/kami/commit/cb9e8bf8ed7faf79de6af828d6c587ffbf2b6ca0, which, when displayed on GitHub, presents the warning
```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```
So maybe that's the *actual* problem, and you first have to fast-forward kami's rv32i branch to that commit (or merge, which creates a merge commit with a new commit hash, and then set it to that one on this PR too).

**Comment by andres-erbsen** [comment]
The submodule is as intended and doing the same used to work before (but perhaps not since pylevellang CI logic). The submodule in this commit points to https://github.com/andres-erbsen/kami/tree/export-hint-extern-bool, I intended to wait for both repositories' CI to pass in parallel and then simultaneously upstream both commits (with the same hash, without creating a mere commit in kami).

Being able to do this seems quite important to me. The goals are roughly to (1) only push to master once all CI targets have passed in all repos (2) not pollute submodule master history with changes that did not pass in downstream repos (3) run CI at all levels in parallel. This strategy has been my primary workflow for stacked changes in coqutil, bedrock2, and fiat-crypto and I would like to resume doing that once the build is fixed. (here the stack involves coq, kami, and bedrock2, but kami is not a submodule). [Concurrent changes are another challenge to this strategy but I have had to abort and retry infrequently enough that I haven't really looked into setting up a commit queue].

I'll rerun this PR just on the off chance this failure was a flake; https://github.com/mit-plv/bedrock2/pull/326 was similar but I may have delayed opening the bedrock2 PR until Kami passed to avoid pinging you with a change I wasn't sure would pass. If this PR still does not pass, I would like to revert the changes that made it not pass.

**Comment by andres-erbsen** [comment]
Rerun failed, let's see if it succeeds after pushing to kami rv32i.

**Comment by andres-erbsen** [comment]
Github timestamps agree that I reopened this issue after "merging" https://github.com/mit-plv/kami/pull/34 and this PR still fails.

**Pull request merged**
