### PR TITLE
Adapt to https://github.com/coq/coq/pull/18590

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/18590
Adopting solution chosen in https://github.com/coq/coq/pull/18590#issuecomment-1927312592

### CODE REVIEW

**Comment by samuelgruetter** [comment]
The build failure seems spurious. I'm about to cherry-pick this on top of my change to drop 8.18 support, should be on master soon.

**Comment by samuelgruetter** [comment]
Cherry-picked onto bedrock2's master branch in [this commit](https://github.com/mit-plv/bedrock2/commit/220fd642995c9025cda904587547aa0c63e32420), and also opened a [fiat-crypto PR](https://github.com/mit-plv/fiat-crypto/pull/1818)

**Comment by proux01** [comment]
Thanks a lot

**Comment by samuelgruetter** [comment]
Thank you for helping us keep bedrock2 compatible! Closing because GitHub doesn't recognize it was already cherry-picked

**Pull request closed without merging**
