### PR TITLE
port examples to NotationsCustomEntry

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
also a refactor of [Demos.v](https://github.com/mit-plv/bedrock2/pull/164/files#diff-810973b8b05d91b3de482c92ca2dac19), @samuelgruetter that ok?

**Comment by samuelgruetter** [comment]
> also a refactor of [Demos.v](https://github.com/mit-plv/bedrock2/pull/164/files#diff-810973b8b05d91b3de482c92ca2dac19), @samuelgruetter that ok?

Yes :+1: 

Is there a way to reuse the entry for a Z literal of constr in the custom grammar for bedrock2 exprs, so that you could write `42` instead of `constr:(42)`?

**Comment by andres-erbsen** [comment]
https://github.com/coq/coq/pull/11561

**Comment by andres-erbsen** [comment]
565ea135598dc76386064c60643c41256c19f097

**Pull request closed without merging**
