### PR TITLE
Overlay for PR #9918 - refer to the right submodule for Kami

### PR DESCRIPTION
**Pull request by mattam82**
Well this is not ideal, I updated my PR on Kami but bedrock2 is not in sync with the branch of Kami. How should we do this?

### CODE REVIEW

**Comment by mattam82** [comment]
This is for coq/coq#9918

**Comment by samuelgruetter** [comment]
Can't we first merge https://github.com/mit-plv/kami/pull/9 so that we don't have to change `.gitmodules` here?

**Comment by mattam82** [comment]
So we'll just update the submodule here to point to the commit at the HEAD after merging mit-plv/kami#9 ? That's fine with me. We can close this when that happens.

**Comment by joonwonc** [comment]
Actually the current head of Kami (https://github.com/mit-plv/kami/commit/d9033b9dc4b7fd323dcbcb77c8c9419b8723dcfc) has a few more changes, nothing to do with this PR, that breaks the bedrock2 build. I have a patch but haven't committed it yet. @samuelgruetter, how do you want to smoothly merge this PR and my bedrock2 changes along with the other Kami changes?

**Comment by samuelgruetter** [comment]
@joonwonc if you just push your patch, referencing to the latest kami, then everything should work and this PR will not be needed, I guess?

**Comment by joonwonc** [comment]
That should work; working on it right now.

**Comment by joonwonc** [comment]
Okay, I've just pushed all the things: the latest Kami, where the PR is applied to, and a related patch  for Bedrock2 to work.

**Pull request closed without merging**
