### PR TITLE
import fnspec from Rupicola

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
@cpitclaudel please take a quick look at https://github.com/mit-plv/bedrock2/pull/177/files#diff-11416abcee82653aa6a8403a95cf17bee4b39bc09149b0b26ba4357a35ee9ed5 (and if the CI has passed, feel free to merge so that you can remove duplication from rupicola).

**Comment by andres-erbsen** [comment]
Actually this might be better placed in WeakestPrecondition.v

**Review by cpitclaudel — APPROVED** [review]
LGTM!  Can you put a pointer in the commit message to https://github.com/mit-plv/rupicola/commit/a9826dfc4777ff2cf38d6f32c2b7d5115d7a7aa1 to connect the histories?

**Comment by cpitclaudel** [comment]
> LGTM! Can you put a pointer in the commit message to mit-plv/rupicola@a9826df to connect the histories?

(or not ^^)

**Pull request merged**
