### PR TITLE
Arrays and structs

### PR DESCRIPTION
**Pull request by gmalecha**
This extends the simple type system to allow fixed-size arrays within types.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
The diff that Github shows me looks like you want to undo https://github.com/mit-plv/bedrock2/commit/c84c64c9babf05910ef166b629dae81d2785ebbc, is this intended?

**Comment by gmalecha** [comment]
It isn't important. Just an artifact of the branch I was working on. I can remove it.

**Comment by samuelgruetter** [comment]
Yeah could you please remove the undoing of c84c64c, because otherwise it looks cool and I'd like to merge it!

**Comment by gmalecha** [comment]
@samuelgruetter I believe this is fixed now.

**Comment by samuelgruetter** [comment]
Thanks!

**Pull request merged**
